spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/baemin
    username: root
    password: a12345678
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
  jwt.secret: jwt-secret
  
